In [1]:
import sys
print(sys.version)

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]


In [ ]:
python.org ==> CPython - GIL is enabled   => pip install numpy pip install pandas ... ... ...

IPython - GIL is disabled 


In Python - Class and Object
            ================

Python native type/class - int float complex str bytes list tuple dict set

In [ ]:
i = 10 # initialization

10 - 0x1234
11 - 0x3452
12 - 0x3234

In [3]:
a = 10
b = 3+7
c = 2+8
print(hex(id(a)))
print(hex(id(b)))
print(hex(id(c)))
print(hex(id(10)))

0x7ffb5f4eb4c8
0x7ffb5f4eb4c8
0x7ffb5f4eb4c8
0x7ffb5f4eb4c8


In [ ]:
product 
   |->productID    - 101  - int
   |->productName  - 'pA'  - str
   |->productCost  - 1000.32 - float
   |->productStatus - True   - bool
    Vs
product_info1 = [101,'pA',1000.32,True] <== list - Collection of different types of items
                                       <== list - mutable(we can add/modify/delete)
    Vs
product_info2 = (101,'pA',1000.32,True) <== tuple - Collection of different types of items
                                             |__ immutable - we can't add/modify/delete 
    Vs
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True} <== dict - Collection of different types of items
                                                                         |-- mutable (we can add/modify/delete)

In [ ]:
dict of list -> d={'Key1':[],'Key2':[],'Key3':[]} # 1Key ->Multiple values 
list of dict -> L=[{},{},{},{}] # index based 

In [5]:
# How to add new data to an existing dict? 
# dictName['newKey'] = value

product_info1 = {} # empty dict

product_info1['pid'] = [101,102,103] 
product_info1['pname'] = ['pA','pB','pC']
product_info1['pcost'] = [1000,2000,3000]
print(product_info1)

{'pid': [101, 102, 103], 'pname': ['pA', 'pB', 'pC'], 'pcost': [1000, 2000, 3000]}


In [6]:
import pprint
pprint.pprint(product_info1)

{'pcost': [1000, 2000, 3000],
 'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC']}


In [7]:
# list of dict -> L=[{},{},{},{}] # index based 

product_info2 = [{'pid':101,'pname':'pA','pcost':1000},
                 {'pid':102,'pname':'pB','pcost':2000},
                 {'pid':103,'pname':'pC','pcost':3000}]

In [10]:
print(product_info2[0]['pname']) # list of dict
print(product_info1['pname'][0]) # dict of list

pA
pA


In [ ]:
numpy - Computation
  |-> index,slicing,reshaping
  |-> ufunctions

pandas - Analysis 
  |-> Series
  |-> DataFrame 

matplotlib - Visualization 
  |-> plot,scatter,bar,pie ...
|
EDA

In [11]:
L = [10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [15]:
import array
#help(array)
arr = array.array('i',[10,20,30,40,50])
L.append(4.5)
arr.append(55) # Vs arr.append(4.5)

In [16]:
arr

array('i', [10, 20, 30, 40, 50, 55])

In [17]:
import numpy
numpy.array(L)

array([10. , 20. , 30. , 40. , 50. ,  4.5,  4.5])

In [18]:
arr = numpy.array(L)
arr+100

array([110. , 120. , 130. , 140. , 150. , 104.5, 104.5])

In [20]:
arr = numpy.array(L)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

float64
(7,)
1


In [22]:
numpy.array([10,20.34,True,'data']).dtype

dtype('<U32')

In [23]:
numpy.array([10,20.34,True,'data']).ndim

1

In [26]:
print(numpy.array([[10,20.34,True,'data']]).ndim)
numpy.array([[10,20.34,True,'data']]).shape

2


(1, 4)

In [29]:
arr = numpy.array([[10,20.34,True,'data']])
print(arr[0][0])

10


In [30]:
arr+100

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('int64')) -> None

In [32]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print(arr.ndim,arr.shape)
print(arr)

2 (2, 3)
[[10 20 30]
 [40 50 60]]


In [33]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
arr.reshape(-1,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [35]:
np.array([1,2,3]).reshape(-1,1).ndim

2

In [ ]:
pandas
 |->Series
 |->DataFrame

In [38]:
import pandas
print(pandas.Series)
print(pandas.DataFrame)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


In [ ]:
pandas/
     |__core/
           |__series.py
                 |--> class Series:
                            ...
     |__core/
           |__frame.py
                 |--> class DataFrame:
                             ...

In [39]:
import pandas as pd
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [40]:
pd.DataFrame([10,20,30])

0
0  10
1  20
2  30

In [41]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [42]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [43]:
df1 = pd.DataFrame(products)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     3 non-null      int64 
 1   pname   3 non-null      object
 2   pcost   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [44]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [45]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [46]:
len(df1.columns)

3

In [47]:
df1

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [48]:
df1.loc[1] # row based access

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [49]:
df1['pname'] # column based access

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [50]:
df1['pid']

0    101
1    102
2    103
Name: pid, dtype: int64

In [51]:
df1.loc[1]['pname'] # Row X Column ->data

'pB'

In [52]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]


In [53]:
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pE')
products['pcost'].append(5000)
products

{'pid': [101, 102, 103, 104, 105, 106],
 'pname': ['pA', 'pB', 'pC', 'pD', 'pE', 'pE'],
 'pcost': [1000, 2000, 3000, 4000, 5000, 5000]}

In [54]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     6 non-null      int64 
 1   pname   6 non-null      object
 2   pcost   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes


In [55]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [56]:
df2.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [57]:
df2.loc[2:] # from 2nd row to list of all - slicing 

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [58]:
df2.loc[2:4] # from 2nd row to 4th row

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000

In [59]:
df2.loc[2:4]['pname']

2    pC
3    pD
4    pE
Name: pname, dtype: object

In [60]:
df2.loc[2][['pname','pcost']]

pname      pC
pcost    3000
Name: 2, dtype: object

In [61]:
df2.loc[2:4][['pname','pcost']]

pname  pcost
2    pC   3000
3    pD   4000
4    pE   5000

In [62]:

df2['pcost']

0    1000
1    2000
2    3000
3    4000
4    5000
5    5000
Name: pcost, dtype: int64

In [63]:
df2['pcost'] >2800

0    False
1    False
2     True
3     True
4     True
5     True
Name: pcost, dtype: bool

In [64]:
df2[df2['pcost'] >2800] # supports boolen index

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [ ]:
# In pandas DF - mutable - inplace=True  <== modified input dataframe

In [65]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [66]:
# To delete a particular row/record 
# df.drop(rowIndex)
df2.drop(3)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pE   5000

In [67]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [68]:
df3 = df2.drop(3)
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pE   5000

In [69]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pE   5000

In [70]:
df3.index

Index([0, 1, 2, 4, 5], dtype='int64')

In [71]:
df3.drop(4,inplace=True) # ->None but dataframe is updated 

In [72]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pE   5000

In [73]:
# To drop columns
df3.drop(columns='pname')

pid  pcost
0  101   1000
1  102   2000
2  103   3000
5  106   5000

In [74]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pE   5000

In [75]:
df3.drop(columns=['pname','pcost'])

pid
0  101
1  102
2  103
5  106

In [76]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pE   5000

In [77]:
# rename columns
# -------------------
# {'oldColumnName':'newColumn'}

d={'K1':[1,2,3],'K2':[4,3,1],'Field 3':[10,23,34]}

df4 = pd.DataFrame(d)
df4.columns

Index(['K1', 'K2', 'Field 3'], dtype='object')

In [78]:
df4

K1  K2  Field 3
0   1   4       10
1   2   3       23
2   3   1       34

In [79]:
df4.rename(columns={'Field 3':'K3'})

K1  K2  K3
0   1   4  10
1   2   3  23
2   3   1  34

In [80]:
df4.rename(columns={'Field 3':'K3'},inplace=True)

In [81]:
df4.columns

Index(['K1', 'K2', 'K3'], dtype='object')

In [82]:
d={}
d['K1']=[10,20,None]
d['K2']=[15,None,None]
d['K3']=[None,11,None]
pd.DataFrame(d)

K1    K2    K3
0  10.0  15.0   NaN
1  20.0   NaN  11.0
2   NaN   NaN   NaN

In [83]:
df5 = pd.DataFrame(d)
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   K1      2 non-null      float64
 1   K2      1 non-null      float64
 2   K3      1 non-null      float64
dtypes: float64(3)
memory usage: 204.0 bytes


In [84]:
df5.isnull()

K1     K2     K3
0  False  False   True
1  False   True  False
2   True   True   True

In [85]:
df5.isnull().sum()

K1    1
K2    2
K3    2
dtype: int64

In [86]:
# To replace NaN value => fillna(<replacementValue>)

df5.fillna('Testdata')

K1        K2        K3
0      10.0      15.0  Testdata
1      20.0  Testdata      11.0
2  Testdata  Testdata  Testdata

In [87]:
df5.fillna(45)

K1    K2    K3
0  10.0  15.0  45.0
1  20.0  45.0  11.0
2  45.0  45.0  45.0

In [89]:
df5['K1']

0    10.0
1    20.0
2     NaN
Name: K1, dtype: float64

In [90]:
df5['K1'].fillna(45)

0    10.0
1    20.0
2    45.0
Name: K1, dtype: float64

In [91]:
df5[['K2','K3']].fillna(56.31)

K2     K3
0  15.00  56.31
1  56.31  11.00
2  56.31  56.31

In [94]:
df5.fillna(56.31,inplace=True)

In [95]:
df5

K1     K2     K3
0  10.00  15.00  56.31
1  20.00  56.31  11.00
2  56.31  56.31  56.31

In [96]:
df5.isnull().sum()

K1    0
K2    0
K3    0
dtype: int64

In [97]:
df5.duplicated()

0    False
1    False
2    False
dtype: bool

In [98]:
df5.duplicated().sum()

np.int64(0)

In [100]:
d={'K1':[10,10,30],'K2':[10,10,30],'K3':[10,10,30]}
df6 = pd.DataFrame(d)
df6.duplicated().sum()

np.int64(1)

In [102]:
df6.duplicated()

0    False
1     True
2    False
dtype: bool

In [103]:
df6

K1  K2  K3
0  10  10  10
1  10  10  10
2  30  30  30

In [104]:
df6.drop_duplicates()

K1  K2  K3
0  10  10  10
2  30  30  30

In [105]:
df6.drop_duplicates(inplace=True)

In [106]:
df6

K1  K2  K3
0  10  10  10
2  30  30  30

In [108]:
d={'K1':[10,20,30],'K2':[15,None,None],'K3':[45,15,None],'K4':[11,12,13]}
df6 = pd.DataFrame(d)
print(df6)
df6.dropna()

   K1    K2    K3  K4
0  10  15.0  45.0  11
1  20   NaN  15.0  12
2  30   NaN   NaN  13


K1    K2    K3  K4
0  10  15.0  45.0  11

In [110]:
df6.dropna(axis=1) # drop column with any NaN value

K1  K4
0  10  11
1  20  12
2  30  13

In [112]:
# help(df6.dropna)

In [113]:
d={}
d['K1']=[10,20,30]
d['K2']=[15,None,None]
d['K3']=[45,11,None]
d['K4']=[1,2,3]
d['K5']=[10,None,None]
d

{'K1': [10, 20, 30],
 'K2': [15, None, None],
 'K3': [45, 11, None],
 'K4': [1, 2, 3],
 'K5': [10, None, None]}

In [114]:
df7 = pd.DataFrame(d)
df7.dropna(thresh=3)

K1    K2    K3  K4    K5
0  10  15.0  45.0   1  10.0
1  20   NaN  11.0   2   NaN

In [115]:
df7.dropna(axis='columns',thresh=3)

K1  K4
0  10   1
1  20   2
2  30   3

In [116]:
df1

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [117]:
df1.loc[1]['pcost']

np.int64(2000)

In [ ]:
# To modify nth cell
# df.at[rowIndex,columnIndex] = updatedvalue ->None

In [118]:
df1

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [119]:
df1.at[1,'pcost'] = 3489.31

C:\Users\karth\AppData\Local\Temp\ipykernel_29236\1321374637.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3489.31' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.at[1,'pcost'] = 3489.31


In [120]:
df1

pid pname    pcost
0  101    pA  1000.00
1  102    pB  3489.31
2  103    pC  3000.00

In [122]:
import numpy as np
np.array([[10,20,30,40],[50,60,70,80]]).shape

(2, 4)

In [129]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0][3])

40


In [128]:
print(arr[0,3])

40


In [133]:
df6
df6.to_csv('r1.csv')

In [134]:
pd.read_csv('r1.csv')

Unnamed: 0  K1    K2    K3  K4
0           0  10  15.0  45.0  11
1           1  20   NaN  15.0  12
2           2  30   NaN   NaN  13

In [135]:
df6.to_csv('r1.csv',index=False)
pd.read_csv('r1.csv')

K1    K2    K3  K4
0  10  15.0  45.0  11
1  20   NaN  15.0  12
2  30   NaN   NaN  13

In [130]:
# pd.read_csv(<inputFile>) Vs pd.DataFrame(<DataStructure>) 

pd.read_csv('emp.csv')

eid    ename  edept    ecity  ecost
0  101      raj  sales     pune   1000
1  102      leo   prod   bglore   2301
2  230      raj   prod     pune   2300
3  450     shan  sales   bglore   3401
4  542      anu     HR   mumbai   4590
5  321     bibu  sales      hyd   5419
6  651      ram     hr   bglore   3130
7  541      leo  admin  chennai   4913
8  652  karthik  sales   bglore   3405

In [131]:
df_csv = pd.read_csv('emp.csv')
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   eid     9 non-null      int64 
 1   ename   9 non-null      object
 2   edept   9 non-null      object
 3   ecity   9 non-null      object
 4   ecost   9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes


In [136]:
# 1. Load emp.csv file content to pandas ->df
df_csv = pd.read_csv('emp.csv')
# 2. get info about loaded DataFrame
df_csv.info()
# 3. List of row index and column index
print(df_csv.index)
print(df_csv.columns)
# 4. display shape of the data - Row X Col
print(df_csv.shape)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   eid     9 non-null      int64 
 1   ename   9 non-null      object
 2   edept   9 non-null      object
 3   ecity   9 non-null      object
 4   ecost   9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 492.0+ bytes
RangeIndex(start=0, stop=9, step=1)
Index(['eid', 'ename', 'edept', 'ecity', 'ecost'], dtype='object')
(9, 5)


In [138]:
# 5. Test - any duplicated values are exists ->drop duplicated update to inputdataframe
df_csv.duplicated()
df_csv.duplicated().sum()
df_csv.drop_duplicates(inplace=True)

np.int64(0)

In [139]:
# 6. Test - any NaN values ->drop NaN index based and Column based
df_csv.isnull().sum()
# 7. Test - any NaN => replace NaN - row/column/ (or) global replacement
df_csv.dropna() # default rowbased
df_csv.dropna(axis=1) # columnbased
df_csv.fillna('sampledata') # global replacement
df_csv['edept'].fillna('Common_dept') # specific column based replacement

eid      0
ename    0
edept    0
ecity    0
ecost    0
dtype: int64

In [143]:
# 8. Rename some selective columns - modified input data frame
print(df_csv.columns)
df_csv.rename(columns={'edept':'EDEPT','ecost':'Amount'},inplace=True)
print(df_csv.columns)


Index(['eid', 'ename', 'edept', 'ecity', 'ecost'], dtype='object')
Index(['eid', 'ename', 'EDEPT', 'ecity', 'Amount'], dtype='object')


In [144]:
# 9. drop some selective columns
df_csv.drop(columns=['eid','ecity'])


ename  EDEPT  Amount
0      raj  sales    1000
1      leo   prod    2301
2      raj   prod    2300
3     shan  sales    3401
4      anu     HR    4590
5     bibu  sales    5419
6      ram     hr    3130
7      leo  admin    4913
8  karthik  sales    3405

In [145]:
# 10. Write DataFrame ->external file
df_csv.to_csv('r1.csv',index=False)

In [146]:
pd.read_csv('r1.csv')

eid    ename  EDEPT    ecity  Amount
0  101      raj  sales     pune    1000
1  102      leo   prod   bglore    2301
2  230      raj   prod     pune    2300
3  450     shan  sales   bglore    3401
4  542      anu     HR   mumbai    4590
5  321     bibu  sales      hyd    5419
6  651      ram     hr   bglore    3130
7  541      leo  admin  chennai    4913
8  652  karthik  sales   bglore    3405